### ISSUE TITLE
verify_ssl configuration is not working

### ISSUE THREAD

**Issue by elyezer** [ibutsu/ibutsu-client-python#5]
```
>>> config = ibutsu.Configuration(host="https://ibutsuhost.com/api")
>>> config.verify_ssl = False
>>> with ibutsu.ApiClient(config) as client:
...     projects = ibutsu.ProjectApi(client)
...     projects.get_project_list()
...
Traceback (most recent call last):
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 429, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 773, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1033, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 645, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/ibutsu_client/api/project_api.py", line 292, in get_project_list
    return self.get_project_list_with_http_info(**kwargs)  # noqa: E501
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/ibutsu_client/api/project_api.py", line 388, in get_project_list_with_http_info
    collection_formats=collection_formats)
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/ibutsu_client/api_client.py", line 369, in call_api
    _preload_content, _request_timeout, _host)
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/ibutsu_client/api_client.py", line 185, in __call_api
    _request_timeout=_request_timeout)
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/ibutsu_client/api_client.py", line 393, in request
    headers=headers)
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/ibutsu_client/rest.py", line 234, in GET
    query_params=query_params)
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/ibutsu_client/rest.py", line 212, in request
    headers=headers)
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/urllib3/request.py", line 75, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/elyezer/.virtualenvs/ibutsu-cli/lib/python3.6/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ibutsuhost.com', port=443): Max retries exceeded with url: /api/project (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:877)'),))
```

**Comment by elyezer** [comment]
Investigated this more and it seems that I had a wrong reference of the client (one without the ssl_verify=False) going around. Trying again I am not able to reproduce this, with that said we can consider this as being a false alarm. Sorry for the unnecessary noise.
